---
title: "article-5 Today's obesity epidemic may have been caused by childhood sugar intake decades ago"
description: |
  A short description of the post. throughout this article researchers from the University of TENNESSEE have conducted a study on the timeliness of the time lag between the increase in sugar consumption in childhood and the increase in current obesity rates
author:
  - name: kenmogne momo rabiole
date: 12-16-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Name of the Magazine + Source [URL]:

Science daily, science news, Journal Reference https://www.sciencedaily.com/releases/2019/09/190923164534.htm
 
## Vocabulary 

|  Words from the text                | Synonym / explanation in English                                                                                                                                        |
| ----------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| infant diet                       | the totality of all that a child consumes in childhood                                                                                                                           |
| time period         | precise period in time.                                               |


## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Alex Bentley and al.                       |
| Published in?                | SEPTEMBER 27, 2019                                                       |
| General topic?               |  Impact of childhood diet on the increase in the current obesity rate of the US population                     |
| Procedure/what was examined? | Use of national obesity data collected between 2004 and 1990 by the Centers for Disease Control and Prevention. 
comparison of these obesity rates with annual sugar consumption since 1970 using median per capita rates published by the US Department of Agriculture
 |
| Conclusions/discovery?       |  Knowing that in the United States sugar consumption (between the end of 1990 and 2016) has decreased but not the obesity rate, it can be concluded that the diet in childhood would influence the obesity rate of the current population    |
| Conclusions/discovery?       |  Knowing that in the United States sugar consumption (between the end of 1990 and 2016) has decreased but not the obesity rate, it can be concluded that the diet in childhood would influence the obesity rate of the current population      |



